import type { Metadata } from "next";
import { BoardVisual } from "../../components/board-visual";
import { ConversionBand, PageHero, PageShell, SectionHeading } from "../../components/page-shell";
import { JsonLd } from "../../components/json-ld";
import { breadcrumbJsonLd, pageMetadata } from "../../lib/seo";

export const metadata: Metadata = pageMetadata({ title: "About Our Repair Approach", description: "Northstar Circuit Works is built around clear industrial electronics evaluation, component-level repair, controlled testing, and direct communication.", path: "/about" });

export default function AboutPage() {
  return <PageShell><JsonLd data={breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "About", path: "/about" }])} /><PageHero index="05 / ABOUT" eyebrow="Northstar Circuit Works" title="Precision begins with a clear answer." intro="Our purpose is straightforward: help industrial teams make informed decisions about failed electronics without overstating what can be known before inspection." aside="Repair feasibility and final scope are confirmed after evaluation." />
    <section className="content-section"><div className="container about-purpose"><div><span className="eyebrow">Purpose</span><h2>Return critical electronics to useful service—when repair is technically responsible.</h2></div><div><p className="prose-lead">Northstar Circuit Works is designed around component-level thinking: understand the symptom, inspect the assembly, isolate the fault, define the scope, and proceed only after approval.</p><p>That approach values the customer’s operating context as much as the board on the bench. Equipment identity, failure behavior, environment, and available test conditions all shape the repair plan.</p></div></div></section>
    <section className="content-section cream-section"><div className="container about-board-grid"><div><BoardVisual variant="inspection" label="Industrial circuit board inspection composition" /></div><div className="data-list">{[["01", "Evaluation before conclusion", "Feasibility and scope are determined after inspection."], ["02", "Approval before work", "The customer reviews the quotation before repair begins."], ["03", "Component-level discipline", "Rework targets the confirmed fault path where technically appropriate."], ["04", "Testing with context", "Procedures vary by product type and available test access."], ["05", "Communication without friction", "Board identity, photos, symptoms, and next steps remain in a direct thread."]].map(([n, title, copy]) => <div className="data-row" key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></section>
    <section className="content-section dark-section"><div className="container"><SectionHeading light eyebrow="Repair philosophy" title="Competence without unsupported claims." intro="Trust comes from explicit boundaries, not invented credentials, guarantees, or success statistics." /><div className="philosophy-grid"><article><span>01</span><h3>Describe what is known.</h3><p>Record the board identity, symptoms, physical condition, and test evidence.</p></article><article><span>02</span><h3>Qualify what is possible.</h3><p>Component availability, board damage, and testability influence feasibility.</p></article><article><span>03</span><h3>Communicate the tradeoff.</h3><p>Repair, return, or replacement guidance should reflect technical and operational context.</p></article></div></div></section>
    <section className="content-section"><div className="container split-content"><SectionHeading eyebrow="Communication standard" title="Direct answers at each decision point." /><div><ul className="check-list">{["What identification is still needed", "Whether an evaluation can proceed", "What should be shipped", "What the quotation includes", "When approval is required", "What testing can reasonably be performed", "What warranty options accompany the confirmed scope"].map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>
    <ConversionBand title="Start with the board, label, and symptoms." />
  </PageShell>;
}
